site_name: Fairy Key Wiki
site_url: https://wiki.fairykey.app
docs_dir: docs
repo_name: Fairy Key
repo_url: https://github.com/FairyKey/FairyKey
edit_uri: https://github.com/FairyKey/wiki/edit/main/docs

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent:
        light blue

    # dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: light blue
      accent: light blue
      
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.code.annotate

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true


nav:
  - Home: index.md
  - Getting Started: 
    - Installation: installation.md
    - Usage: usage.md
    - Importing multiple sheets: multipleimport.md
    - Shortcuts: shortcuts.md

  - Features:
    - Transposition Detector v2: transpositionv2.md 

  - Developers:
    - Building: building.md

  - License: licenses.md